# Generated by Django 3.0.3 on 2020-03-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_IP', models.CharField(max_length=100)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SlugTable')),
            ],
        ),
    ]
